const PRIVATE_SERVER_NAME_PREFIX = "pserv-";
const RESERVED_RAM_ON_HOME_SERVER = 16;
const HACK_SCRIPT_NAME = "hack.js";
const GROW_SCRIPT_NAME = "grow.js";
const WEAKEN_SCRIPT_NAME = "weaken.js";
const SHARE_SCRIPT_NAME = "share.js";
const DAEMON_SCRIPT_NAME = "./daemon.js";
const DEFAULT_EXP_FARM_TARGETS = ["joesguns"];
const LOG_FOLDER = "logs";
const STOCK_MARKET_COMMISSION_FEE = 1e5;
const MAX_STOCK_HISTORY_RECORD = 152;
const STOCK_HISTORY_LOGS_PREFIX = `${LOG_FOLDER}/stockHistory/`;
export {
    DAEMON_SCRIPT_NAME,
    DEFAULT_EXP_FARM_TARGETS,
    GROW_SCRIPT_NAME,
    HACK_SCRIPT_NAME,
    LOG_FOLDER,
    MAX_STOCK_HISTORY_RECORD,
    PRIVATE_SERVER_NAME_PREFIX,
    RESERVED_RAM_ON_HOME_SERVER,
    SHARE_SCRIPT_NAME,
    STOCK_HISTORY_LOGS_PREFIX,
    STOCK_MARKET_COMMISSION_FEE,
    WEAKEN_SCRIPT_NAME,
};
